language: java
jdk:
  - oraclejdk8
  - openjdk8
cache:
  directories:
  - "$HOME/.cache"
deploy:
  provider: script
  script: "mvn clean install -Dmaven.test.skip=true -Ptest"
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    recipients:
    - admin@jingdor.com
    on_success: always
    on_failure: always