language: java
jdk:
  - oraclejdk8
  - openjdk8
script:
  - mvn clean package -DskipTests=true
after_success:
  - echo "success"

notifications:
  email:
    recipients:
    - admin@jingdor.com
    on_success: always
    on_failure: always